import { escapeHtml, formatPrice, getWishlist, getCompare, toggleWishlist, toggleCompare, notify, readJSON } from './utils.js';
const img = id => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=85`;
export const products = [
 {id:1,name:'The Form Tee',category:'Men',type:'Clothing',price:28000,oldPrice:35000,rating:4.9,reviews:124,image:img('photo-1521572163474-6864f9cf17ab'),description:'A quietly confident everyday tee in heavyweight, soft-touch cotton. Cut with an easy shape that feels just right.',sizes:['S','M','L','XL'],colors:['Ecru','Black','Olive'],featured:true,isNew:true},
 {id:2,name:'Sunday Linen Shirt',category:'Men',type:'Clothing',price:54000,oldPrice:null,rating:4.8,reviews:86,image:img('photo-1603252109303-2751441dd157'),description:'Airy European linen with a relaxed collar and considered proportions. Your answer to warm afternoons.',sizes:['S','M','L','XL'],colors:['Oat','White','Blue'],featured:true,isNew:true},
 {id:3,name:'Soft Structure Blazer',category:'Women',type:'Clothing',price:98000,oldPrice:125000,rating:4.9,reviews:58,image:img('photo-1591047139829-d91aecb6caea'),description:'A softly tailored layer that brings ease to the everyday. Lightly structured, entirely wearable.',sizes:['XS','S','M','L'],colors:['Sand','Black'],featured:true,isNew:false},
 {id:4,name:'The Column Dress',category:'Women',type:'Clothing',price:76000,oldPrice:null,rating:4.7,reviews:42,image:img('photo-1595777457583-95e059d581b8'),description:'Clean lines, a fluid drape, and a little room to make it your own. An effortless one-piece for wherever the day leads.',sizes:['XS','S','M','L'],colors:['Cocoa','Black'],featured:true,isNew:true},
 {id:5,name:'Everywhere Tote',category:'Bags',type:'Bags',price:42000,oldPrice:null,rating:4.8,reviews:93,image:img('photo-1584917865442-de89df76afd3'),description:'A generous, thoughtfully organized carryall in textured cotton canvas. Made for market mornings and the long way home.',sizes:['One size'],colors:['Natural','Black'],featured:true,isNew:false},
 {id:6,name:'Daybreak Sneaker',category:'Shoes',type:'Shoes',price:69000,oldPrice:82000,rating:4.6,reviews:72,image:img('photo-1542291026-7eec264c27ff'),description:'A pared-back low top with a cushioned sole and a considered finish. Comfort that keeps its composure.',sizes:['38','39','40','41','42','43'],colors:['Chalk','Black'],featured:true,isNew:true},
 {id:7,name:'Everyday Leather Belt',category:'Accessories',type:'Accessories',price:32000,oldPrice:null,rating:4.7,reviews:31,image:img('photo-1624222247344-550fb8f45c5b'),description:'A slim leather belt finished with understated brushed hardware. The detail that quietly pulls it together.',sizes:['S','M','L'],colors:['Tan','Black'],featured:false,isNew:false},
 {id:8,name:'Weekend Knit',category:'Men',type:'Clothing',price:62000,oldPrice:null,rating:4.9,reviews:67,image:img('photo-1576566588028-4147f3842f27'),description:'A fine gauge cotton knit with a softly open texture. Ideal as a layer, lovely on its own.',sizes:['S','M','L','XL'],colors:['Cream','Navy','Sage'],featured:true,isNew:true},
 {id:9,name:'The Relaxed Trouser',category:'Women',type:'Clothing',price:58000,oldPrice:72000,rating:4.8,reviews:49,image:img('photo-1594633312681-425c7b97ccd1'),description:'A fluid, high-waisted trouser that does its best work in motion. The easy foundation for a hundred outfits.',sizes:['XS','S','M','L'],colors:['Stone','Black'],featured:false,isNew:false},
 {id:10,name:'Sculpted Shoulder Bag',category:'Bags',type:'Bags',price:88000,oldPrice:null,rating:4.9,reviews:38,image:img('photo-1590874103328-eac38a683ce7'),description:'A sculptural silhouette in supple vegan leather, sized for the things you actually carry.',sizes:['One size'],colors:['Cocoa','Black'],featured:true,isNew:true},
 {id:11,name:'Weekend Slide',category:'Shoes',type:'Shoes',price:46000,oldPrice:null,rating:4.5,reviews:29,image:img('photo-1543163521-1bf539c55dd2'),description:'A clean-lined slide with a supportive footbed and soft straps. The easiest part of getting ready.',sizes:['37','38','39','40','41'],colors:['Tan','Black'],featured:false,isNew:true},
 {id:12,name:'The Essential Cap',category:'Accessories',type:'Accessories',price:24000,oldPrice:null,rating:4.6,reviews:54,image:img('photo-1588850561407-ed78c282e89b'),description:'A cotton twill cap with a softened crown and an adjustable back. Shade, sorted.',sizes:['One size'],colors:['Olive','Navy','Ecru'],featured:true,isNew:false},
 {id:13,name:'Airy Poplin Shirt',category:'Women',type:'Clothing',price:48000,oldPrice:null,rating:4.8,reviews:33,image:img('photo-1598554747436-c9293d6a588f'),description:'Crisp poplin with a little extra ease. A smart everyday staple that never feels too serious.',sizes:['XS','S','M','L'],colors:['White','Blue'],featured:false,isNew:true},
 {id:14,name:'The Minimal Frame',category:'Accessories',type:'Accessories',price:39000,oldPrice:49000,rating:4.7,reviews:81,image:img('photo-1511499767150-a48a237f0083'),description:'A lightweight acetate frame with sun-ready lenses and a shape that suits a life outdoors.',sizes:['One size'],colors:['Tortoise','Black'],featured:false,isNew:false},
 {id:15,name:'Soft Leather Wallet',category:'Accessories',type:'Accessories',price:35000,oldPrice:null,rating:4.8,reviews:45,image:img('photo-1627123424574-724758594e93'),description:'A compact, beautifully simple wallet with room for the essentials. Made to get better with time.',sizes:['One size'],colors:['Cognac','Black'],featured:true,isNew:false},
 {id:16,name:'Studio Overshirt',category:'Men',type:'Clothing',price:72000,oldPrice:90000,rating:4.9,reviews:37,image:img('photo-1591047139829-d91aecb6caea'),description:'A useful midweight overshirt, cut to layer over the pieces you already love.',sizes:['S','M','L','XL'],colors:['Moss','Sand'],featured:false,isNew:true},
 {id:17,name:'Coastline Polo',category:'Men',type:'Clothing',price:39000,oldPrice:null,rating:4.7,reviews:28,image:img('photo-1627225924765-552d49cf47ad'),description:'A relaxed cotton polo with a clean collar and just enough texture for warm days.',sizes:['S','M','L','XL'],colors:['Navy','Ecru','Olive'],featured:true,isNew:true},
 {id:18,name:'The Everyday Chino',category:'Men',type:'Clothing',price:61000,oldPrice:74000,rating:4.8,reviews:41,image:img('photo-1473966968600-fa801b869a1a'),description:'A versatile straight-leg chino in soft, durable cotton twill. Easy to dress up and even easier to wear.',sizes:['30','32','34','36','38'],colors:['Stone','Navy'],featured:false,isNew:false},
 {id:19,name:'Relaxed Weekend Short',category:'Men',type:'Clothing',price:36000,oldPrice:null,rating:4.6,reviews:19,image:img('photo-1591195853828-11db59a44f6b'),description:'An easy pull-on short with a comfortable waistband and a considered, above-the-knee cut.',sizes:['S','M','L','XL'],colors:['Sand','Black','Olive'],featured:false,isNew:true},
 {id:20,name:'Ribbed Essential Tank',category:'Women',type:'Clothing',price:26000,oldPrice:null,rating:4.8,reviews:63,image:img('photo-1503342217505-b0a15ec3261c'),description:'A soft ribbed cotton tank with a flattering neckline. A reliable first layer for every season.',sizes:['XS','S','M','L'],colors:['White','Black','Cocoa'],featured:true,isNew:true},
 {id:21,name:'The Wrap Blouse',category:'Women',type:'Clothing',price:52000,oldPrice:65000,rating:4.9,reviews:34,image:img('photo-1551803091-e20673f15770'),description:'A fluid wrap blouse that moves easily from workdays to evenings, with a tie waist for your preferred fit.',sizes:['XS','S','M','L'],colors:['Ivory','Blue'],featured:false,isNew:false},
 {id:22,name:'Sunday Midi Skirt',category:'Women',type:'Clothing',price:57000,oldPrice:null,rating:4.7,reviews:26,image:img('photo-1583496661160-fb5886a0aaaa'),description:'A soft, swaying midi skirt with a clean waistband and an easy drape that goes everywhere.',sizes:['XS','S','M','L'],colors:['Black','Cocoa'],featured:false,isNew:true},
 {id:23,name:'The City Loafer',category:'Shoes',type:'Shoes',price:78000,oldPrice:92000,rating:4.8,reviews:47,image:img('photo-1533867617858-e7b97e060509'),description:'A refined everyday loafer with a softly cushioned insole and a streamlined profile.',sizes:['37','38','39','40','41','42'],colors:['Black','Cognac'],featured:true,isNew:true},
 {id:24,name:'Minimal Court Sneaker',category:'Shoes',type:'Shoes',price:64000,oldPrice:null,rating:4.7,reviews:52,image:img('photo-1549298916-b41d501d3772'),description:'A clean court-inspired sneaker with a cushioned footbed and versatile low-profile shape.',sizes:['37','38','39','40','41','42'],colors:['White','Navy'],featured:false,isNew:false},
 {id:25,name:'Market Day Crossbody',category:'Bags',type:'Bags',price:67000,oldPrice:null,rating:4.9,reviews:36,image:img('photo-1548036328-c9fa89d128fa'),description:'A compact crossbody with considered pockets and an adjustable strap, sized for your daily essentials.',sizes:['One size'],colors:['Cocoa','Black','Tan'],featured:true,isNew:true},
 {id:26,name:'Soft Carryall',category:'Bags',type:'Bags',price:79000,oldPrice:96000,rating:4.8,reviews:44,image:img('photo-1591561954557-26941169b49e'),description:'A roomy, lightweight carryall with a relaxed shape for weekends, work, and everything in between.',sizes:['One size'],colors:['Sand','Black'],featured:false,isNew:false},
 {id:27,name:'Everyday Pendant',category:'Accessories',type:'Accessories',price:29000,oldPrice:null,rating:4.8,reviews:22,image:img('photo-1611652022419-a9419f74343d'),description:'A simple pendant on a delicate chain, made to sit just right on its own or alongside your favourites.',sizes:['One size'],colors:['Silver','Gold'],featured:true,isNew:true},
 {id:28,name:'Classic Ribbed Socks · 3 Pack',category:'Accessories',type:'Accessories',price:18000,oldPrice:null,rating:4.6,reviews:57,image:img('photo-1586350977771-b3b0aaa50235'),description:'A three-pair set of soft cotton-rich ribbed socks for all-day comfort and an easy finish.',sizes:['S/M','L/XL'],colors:['White','Charcoal'],featured:false,isNew:false}
];
products.forEach(product => { product.trending = [1, 4, 6, 10, 17, 20, 23, 25, 27].includes(product.id); product.onSale = Boolean(product.oldPrice); product.stock ??= product.id === 14 ? 0 : ([6, 10, 23].includes(product.id) ? 3 : 18 + product.id); product.tags ??= [product.category.toLowerCase(), product.type.toLowerCase()]; product.images ??= [product.image, img('photo-1529139574466-a303027c1d8b'), img('photo-1483985988355-763728e1935b'), img('photo-1515886657613-9f3515b0c78f')]; });
const savedCatalog=readJSON('nova-product-catalog',[]);if(Array.isArray(savedCatalog)){for(const edit of savedCatalog){if(!edit||typeof edit!=='object'||!Number.isInteger(Number(edit.id)))continue;const index=products.findIndex(item=>item.id===Number(edit.id));if(edit.deleted){if(index>=0)products.splice(index,1);continue;}if(typeof edit.name!=='string'||typeof edit.image!=='string'||typeof edit.description!=='string'||!Array.isArray(edit.sizes)||!Array.isArray(edit.colors)||!Number.isFinite(Number(edit.price))||!Number.isFinite(Number(edit.stock)))continue;if(index>=0)Object.assign(products[index],edit);else products.push(edit);}}
export function persistCatalog() { try { const saved=JSON.parse(localStorage.getItem('nova-deleted-products')||'[]'),deleted=Array.isArray(saved)?saved.filter(Number.isInteger):[]; localStorage.setItem('nova-product-catalog', JSON.stringify([...products,...deleted.map(id=>({id,deleted:true}))])); } catch {} }
export function stockState(product) { const stock = Math.max(0, Number(product.stock ?? 10)); return stock === 0 ? 'Out of stock' : stock <= 5 ? `Only ${stock} left` : 'In stock'; }
export function productCard(product, state = {}) { const saved = (state.wishlist||getWishlist()).includes(product.id), compared = (state.compare||getCompare()).includes(product.id), stock = stockState(product), unavailable = Number(product.stock) === 0; const sale = product.oldPrice ? `<span class="sale-tag">- ${Math.round((1-product.price/product.oldPrice)*100)}%</span>` : ''; const trending = product.trending ? '<span class="trending-tag">Trending</span>' : ''; return `<article class="product-card" data-product-id="${product.id}"><div class="product-photo"><a href="product.html?id=${product.id}" aria-label="View ${escapeHtml(product.name)}"><img loading="lazy" width="900" height="1125" src="${escapeHtml(product.image)}" alt="${escapeHtml(product.name)}"></a>${sale}${trending}<span class="stock-badge ${unavailable?'is-out':product.stock<=5?'is-low':''}">${stock}</span><button class="heart-button ${saved?'is-saved':''}" data-wishlist-toggle="${product.id}" aria-label="${saved?'Remove from':'Add to'} wishlist" aria-pressed="${saved}">${saved?'♥':'♡'}</button><div class="card-action-row"><button class="quick-view-trigger" data-quick-view="${product.id}">Quick view</button><button class="quick-add" data-quick-add="${product.id}" ${unavailable?'disabled':''}>${unavailable?'Out of stock':'Add to cart'}</button></div></div><div class="product-card-info"><div><p class="product-category">${escapeHtml(product.category)}</p><a class="product-name" href="product.html?id=${product.id}">${escapeHtml(product.name)}</a></div><div class="price-block"><strong>${formatPrice(product.price)}</strong>${product.oldPrice?`<del>${formatPrice(product.oldPrice)}</del>`:''}</div></div><div class="rating-line"><span>★</span> ${product.rating} <span class="rating-reviews">(${product.reviews})</span></div><button class="compare-toggle ${compared?'is-compared':''}" data-compare-toggle="${product.id}" aria-pressed="${compared}">${compared?'✓ Added to compare':'＋ Compare'}</button></article>`; }
export function renderCards(container, list, options = {}) { if (container) { const state={wishlist:getWishlist(),compare:getCompare(),...options};container.innerHTML = list.map(item => productCard(item, state)).join(''); } }
export function bindProductCards(container, onChange = () => {}) { if (!container) return; container.addEventListener('click', event => { const heart = event.target.closest('[data-wishlist-toggle]'), quick = event.target.closest('[data-quick-add]'), view = event.target.closest('[data-quick-view]'), compare = event.target.closest('[data-compare-toggle]'); if (heart) { const saved = toggleWishlist(heart.dataset.wishlistToggle); heart.classList.toggle('is-saved', saved); heart.setAttribute('aria-pressed', String(saved)); heart.textContent = saved ? '♥' : '♡'; heart.setAttribute('aria-label', `${saved?'Remove from':'Add to'} wishlist`); notify(saved ? 'Added to your wishlist' : 'Removed from your wishlist'); onChange(); } if (quick) { const item = products.find(p => p.id === Number(quick.dataset.quickAdd)); if (item) import('./utils.js').then(({ addToCart, notify }) => { addToCart(item.id, 1, item.sizes[0], item.colors[0]); notify(`${item.name} added to cart`); }); } if (view) window.dispatchEvent(new CustomEvent('nova:quick-view', { detail: { id: Number(view.dataset.quickView) } })); if (compare) { const result = toggleCompare(compare.dataset.compareToggle); if (result.limit) notify('Compare up to three products at a time', 'warning'); else { compare.classList.toggle('is-compared', result.added); compare.setAttribute('aria-pressed', String(result.added)); compare.textContent = result.added ? '✓ Added to compare' : '＋ Compare'; notify(result.added ? 'Added to comparison' : 'Removed from comparison'); } } }); }
